FROM 763104351884.dkr.ecr.us-west-2.amazonaws.com/pytorch-training:1.5.1-gpu-py3
    
RUN apt-get update \
    && apt-get install -y  --allow-downgrades --allow-change-held-packages --no-install-recommends \
    libsndfile1
